# Слова которые будут запрещены в чате

blockedWords:
  - "лох"
  - "тупой"

# Сообщение которое будет отправлятся игроку

blockedWordsMessage: "§fВы §e{player} §fнаписал запрещенное слово: §b{word}. §fСообщение не было отправлено."
blockedDomainsMessage: "§fВы §e{player} §fнаписал сообщение, в котором содержится доменное имя: §b{domain}. §fСообщение не было отправлено."